name: Build

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  build_rg3:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { name: "Windows MSVC", os: windows-latest, cc: "cl", cxx: "cl", boost_toolset: msvc }

    steps:
      # Download repository with submodules
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      # Setup Ninja
      - name: Get latests Ninja
        uses: ashutoshvarma/setup-ninja@master

      # Check cache of Boost & LLVM - take if exists
      # Build Boost 1.81.0
      - name: Install Boost 1.81.0
        uses: MarkusJx/install-boost@v2.4.4
        id: install-boost
        with:
          boost_version: 1.81.0
          toolset: msvc
          link: static

      # Build LLVM 16.0.4
      - name: Download LLVM
        uses: llvm/actions/get-llvm-project-src@main
        with:
          ref: "llvmorg-16.0.4"

      # Build project via cmake
      # Build python whl packages
      # Compress things
      # Send artifacts to GitHub