name: Build

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  build_rg3:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { name: "Windows MSVC", os: windows-latest, cc: "cl", cxx: "cl", boost_toolset: msvc }

    steps:
      # Download repository with submodules
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      # Setup Ninja
      - name: Get latests Ninja
        uses: ashutoshvarma/setup-ninja@master

      # Check cache of Boost & LLVM - take if exists
      # Build Boost 1.81.0
      # Build LLVM 15.0.0
      # Build project via cmake
      # Compress artifacts
      # Send artifacts to GitHub